import MainHead from "./components/Layout/MainHead";
import Header from "./components/Layout/Header";
import Footer from "./components/Layout/Footer";
import "./globals.css";
import Head from "next/head";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Cookie Stand Admin',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <MainHead></MainHead>
      </Head>
      <body className="min-h-screen">
        <header>
          <Header />
        </header>
        <main>
          <div>{children}</div>
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
